apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- notebook_template.yaml
- github.com/kubeflow/kubeflow/components/crud-web-apps/jupyter/manifests/overlays/istio?ref=0e91a2b9cd0c3b6687692b1f1f09ac6070cc6c3e # tag=v1.3.0
#- github.com/paloul/argoflow-kubeflow/components/crud-web-apps/jupyter/manifests/overlays/istio?ref=aibeyond-jupyterwebapp-customization

patchesStrategicMerge:
- spawner_ui_config.yaml
- logos-configmap.yaml
- deployment.yaml

images:
- name: 562046374233.dkr.ecr.us-west-2.amazonaws.com/ai.beyond/babylon/kubeflow/jupyter-web-app
  newName: 562046374233.dkr.ecr.us-west-2.amazonaws.com/ai.beyond/babylon/kubeflow/jupyter-web-app
  newTag: v1.3.0

#- name: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app
#  newName: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app
#  newTag: v1.3.0

