apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hawkeye-perfecta-api
  namespace: hawkeye-perfecta
spec:
  gateways:
  - hawkeye-perfecta-gateway
  hosts:
  - perfecta.hawkeye.beyond.ai
  http:
  - headers:
      request:
        set:
          Access-Control-Allow-Origin: "http://localhost:3000"
          Access-Control-Allow-Methods: "POST, GET, OPTIONS, DELETE"
    route:
    - destination:
        host: hawkeye-perfecta-api.hawkeye-perfecta.svc.cluster.local
        port:
          number: 5000
