apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hawkeye-perfecta-api
  namespace: hawkeye-perfecta
spec:
  gateways:
  - hawkeye-perfecta-gateway
  hosts:
  - perfecta.hawkeye.beyond.ai
  http:
  - route:
    - destination:
        host: hawkeye-perfecta-api.hawkeye-perfecta.svc.cluster.local
        port:
          number: 5000
    corsPolicy:
      allowCredentials: true
      allowMethods:
      - GET
      - HEAD
      - POST
      - OPTIONS
      maxAge: "24h"
      allowOrigins:
      - exact: "http://localhost:3000"
