apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hawkeye-perfecta-api
  namespace: hawkeye-perfecta
spec:
  gateways:
  - hawkeye-perfecta-gateway
  hosts:
  - perfecta.hawkeye.beyond.ai
  http:
  - route:
    - destination:
        host: hawkeye-perfecta-api.hawkeye-perfecta.svc.cluster.local
        port:
          number: 5000
    corsPolicy:
      allowCredentials: true
      allowHeaders:
      - authorization
      - proxy-authorization
      - content-type
      - x-forwarded-access-token
      - x-forwarded-user
      - x-forwarded-email
      allowMethods:
      - GET
      - POST
      allowOrigin:
      - http://localhost:3000
      allowOrigins:
      - exact: http://localhost:3000
