apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hawkeye-perfecta-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: hawkeye-perfecta-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  commonName: perfecta.hawkeye-meit.beyond.ai
  dnsNames:
    - perfecta.hawkeye-meit.beyond.ai
