apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hawkeye
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paloul/ls-deployment.git
    targetRevision: hawkeye-meit
    path: ./distribution
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
