apiVersion: v1
kind: ServiceAccount
metadata:
  name: fsx-csi-controller-sa
  namespace: kubeflow
  #Enable if EKS IAM for SA is used
  annotations:
    eks.amazonaws.com/role-arn: <<__role_arn.fsx_csi_driver__>>