  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsx-claim-sample
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx
  resources:
    requests:
      storage: <<__fsx_lustre.storage_request__>>
# Update spec.resource.requests.storage with the storage capacity to request. 
# The storage capacity value will be rounded up to 1200 GiB, 2400 GiB, or a multiple of 3600 GiB for SSD. 
# If the storageType is specified as HDD, the storage capacity will be rounded up to 6000 GiB or a multiple 
# of 6000 GiB if the perUnitStorageThroughput is 12, or rounded up to 1800 or a multiple of 1800 if the 
# perUnitStorageThroughput is 40.