kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fsx
provisioner: fsx.csi.aws.com
mountOptions:
  - flock
parameters:
  subnetId: <<__fsx_lustre.subnet_id__>>
  securityGroupIds: <<__fsx_lustre.security_group_id__>>
  deploymentType: <<__fsx_lustre.deployment_type__>>
  storageType: <<__fsx_lustre.storage_type__>>
  perUnitStorageThroughput: "<<__fsx_lustre.storage_throughput__>>"
  driveCacheType: <<__fsx_lustre.drive_cache_type__>>
  automaticBackupRetentionDays: "1"
  dailyAutomaticBackupStartTime: "00:00"
  copyTagsToBackups: "true"
  # subnetId - the subnet ID that the FSx for Lustre filesystem should be created inside.
  # securityGroupIds - a common separated list of security group IDs that should be attached to the filesystem
  # deploymentType (Optional) - FSx for Lustre supports three deployment types, SCRATCH_1, SCRATCH_2 and PERSISTENT_1. Default: SCRATCH_1.
  # kmsKeyId (Optional) - for deployment type PERSISTENT_1, customer can specify a KMS key to use.
  # perUnitStorageThroughput (Optional) - for deployment type PERSISTENT_1, customer can specify the storage throughput. Default: "200". 
  #   Note that customer has to specify as a string here like "200" or "100" etc.
  # storageType (Optional) - for deployment type PERSISTENT_1, customer can specify the storage type, either SSD or HDD. Default: "SSD"
  # driveCacheType (Required if storageType is "HDD") - for HDD PERSISTENT_1, specify the type of drive cache, either NONE or READ.
  # automaticBackupRetentionDays (Optional) - The number of days to retain automatic backups. The default is to retain backups for 7 days. 
  #   Setting this value to 0 disables the creation of automatic backups. The maximum retention period for backups is 35 days
  # dailyAutomaticBackupStartTime (Optional) - The preferred time to take daily automatic backups, formatted HH:MM in the UTC time zone.
  # copyTagsToBackups (Optional) - A boolean flag indicating whether tags for the file system should be copied to backups. 
  #   This value defaults to false. If it's set to true, all tags for the file system are copied to all automatic and user-initiated 
  #   backups where the user doesn't specify tags. If this value is true, and you specify one or more tags, only the specified tags 
  #   are copied to backups. If you specify one or more tags when creating a user-initiated backup, no tags are copied from the file 
  #   system, regardless of this value.