apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
        - name: ml-pipeline-api-server        
          image: public.ecr.aws/atcommons/pipelines/backend:latest #For debugging only!
          env:
                  
            # S3 params
            - name: OBJECTSTORECONFIG_BUCKETNAME
              valueFrom:
                configMapKeyRef:
                  name: pipelines-s3-config
                  key: BUCKET_NAME                  
            - name: OBJECTSTORECONFIG_PIPELINEFOLDER
              valueFrom:
                configMapKeyRef:
                  name: pipelines-s3-config
                  key: PIPELINE_FOLDER
            - name: OBJECTSTORECONFIG_PIPELINEPATH
              valueFrom:
                configMapKeyRef:
                  name: pipelines-s3-config
                  key: PIPELINE_PATH
            - name: OBJECTSTORECONFIG_REGION
              valueFrom:
                configMapKeyRef:
                  name: pipelines-s3-config
                  key: REGION

            # Params to remove (referenced from non-existent secret).
            - $patch: delete
              name: OBJECTSTORECONFIG_ACCESSKEY
            - $patch: delete
              name: OBJECTSTORECONFIG_SECRETACCESSKEY

            # # Default params
            # - name: OBJECTSTORECONFIG_SECURE
            #   value: true
            # - name: OBJECTSTORECONFIG_HOST
            #   value: s3.amazonaws.com
            # - name: INITCONNECTIONTIMEOUT
            #   value: 6m
            # - name: DEFAULTPIPELINERUNNERSERVICEACCOUNT
            #   value: pipeline-runner

          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: ml-pipeline-config
          items:
            # Note that due to how the api-server has been set up, both config.json and sample_config.json must be mounted into the folder /config, even if no changes have been made to one of them
            - key: config.json
              path: config.json
            - key: sample_config.json
              path: sample_config.json
