apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: grizzo
spec:
  owner:
    kind: User
    name: grizzo@beyond.ai
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-adnoc-hck-pv-grizzo
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: efs-sc
  claimRef:
    name: efs-adnoc-hck
    namespace: grizzo
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-4f415248::fsap-0a980abfa5232b806 # This is the important piece. The same efs vol access point is shared for a project
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-adnoc-hck
  namespace: grizzo
spec:
  storageClassName: efs-sc
  volumeName: efs-adnoc-hck-pv-grizzo
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi