apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateways-issuer
spec:  
  selfSigned:
    $patch: delete
  acme:
    # ACME Server options:
      # https://acme-v02.api.letsencrypt.org/directory - Used to generate valid cert, but has rate limits, use for prod
      # https://acme-staging-v02.api.letsencrypt.org/directory - Used to generate dev cert without rate limits when deploying a lot
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@beyond.ai
    privateKeySecretRef:
      name: gateways-issuer-account-key
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z08066803J8DOKIDP5E43
          region: ap-southeast-1
          # role: arn:aws:iam::113151489485:role/eksctl-hawkeye-meit-addon-iamserviceaccount-Role1-CP43OZFJSJO7
