apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::113151489485:role/eksctl-hawkeye-meit-addon-iamserviceaccount-Role1-CP43OZFJSJO7
