apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:

    # https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller/1.2.0

    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.2.0
    chart: aws-load-balancer-controller
    helm:
      parameters:
        - name: serviceAccount.name
          value: <<__serviceAccount_name.aws_load_balancer__>>
        - name: clusterName
          value: <<__cluster_name__>>
        - name: image.repository
          value: amazon/aws-alb-ingress-controller
        - name: vpcId
          value: <<__vpc_id__>>
        - name: region
          value: <<__aws_region__>>
        - name: serviceAccount.create
          value: "false"
        - name: rbac.create
          value: "true"
        - name: resources.limits.cpu
          value: 100m
        - name: resources.limits.memory
          value: 300Mi
        - name: resources.requests.cpu
          value: 100m
        - name: resources.requests.memory
          value: 300Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
