apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-node-termination-handler
  namespace: argocd
spec:
  project: default
  source:
    # Link to helm chart 
    # https://artifacthub.io/packages/helm/aws/aws-node-termination-handler
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 0.15.0 # Chart v0.15.0 uses v1.13.0 of the node-termination-handler
    chart: aws-node-termination-handler
    helm:
     parameters:
      - name : "enableSpotInterruptionDraining"
        value : "true"
      - name : "enableScheduledEventDraining"
        value : "true"
      - name : "nodeSelector.lifecycle"
        value : Ec2Spot
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
