apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.10.5
    chart: cluster-autoscaler
    helm:
      parameters:
        - name: serviceAccount.name
          value: <<__serviceAccount_name.cluster_autoscaler__>>
        - name: serviceAccount.create
          value: "false"
        - name: rbac.create
          value: "true"
        - name: fullnameOverride
          value: cluster-autoscaler
        - name: cloudProvider
          value: aws
        - name: image.repository
          value: k8s.gcr.io/autoscaling/cluster-autoscaler
        - name: image.tag
          value: v1.21.0
        - name: autoDiscovery.clusterName
          value: <<__cluster_name__>>
        - name: autoDiscovery.enabled
          value: "true"
        - name: awsRegion
          value: <<__aws_region__>>
        - name: extraArgs.balance-similar-node-groups
          value: "true"
        - name: extraArgs.scale-down-enabled
          value: "true"
        - name: rbac.create
          value: "true"
        - name: rbac.pspEnabled
          value: "true"
        - name: resources.limits.cpu
          value: 100m
        - name: resources.limits.memory
          value: 300Mi
        - name: resources.requests.cpu
          value: 100m
        - name: resources.requests.memory
          value: 300Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
