apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paloul/ls-deployment.git
    targetRevision: hawkeye
    path: distribution/oidc-auth/base
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
