apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- secret.yaml
- configmap.yaml
- database-creation-job.yaml
- deployment.yaml
- service.yaml
- virtual-service.yaml
- mlflow-gateway-cert.yaml
- mlflow-gateway.yaml
