apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- envoy-filter-ingressgateway-settings.yaml
- envoy-filter-proxy-protocol.yaml
- envoy-filter-cors-bypass.yaml
- gateway-authorizationpolicy.yaml
- ingress-class.yaml
- cluster-local-gateway.yaml
- cluster-local-gateway-authorizationpolicy.yaml
- deny-all-authorizationpolicy.yaml
# - monitoring/
